name: Monorepo CI

on:
  pull_request:
    branches: [dev, main]

jobs:
  detect-changes:
    name: Detect Changed Packages
    runs-on: ubuntu-latest
    outputs:
      backend:  ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  backend-ci:
    name: Backend CI
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend == 'true' }}
    uses: ./.github/workflows/backend-ci.yml

  frontend-ci:
    name: Frontend CI
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/frontend-ci.yml
